---
- name: Prepare
  hosts: localhost
  gather_facts: true
  tasks:
    - name: Pull image jenkins
      docker_image:
        name: jenkins

    - name: Container jenkins master
      docker_container:
        name: jenkins_master
        image: jenkins
        ports:
          - "8080:8080"
          - "50000:50000"

    - name: Check path password for jenkins master
      command: docker exec -i jenkins_master ls -ld /var/jenkins_home/secrets/initialAdminPassword
      register: jenkins_master_password_path
      retries: 5
      delay: 10
      until: jenkins_master_password_path.stdout_lines
